export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const REMOVE_TASK_REQUEST = "REMOVE_TASK_REQUEST";
export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";
